In [2]:
import numpy as np 

STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253
 
np.random.seed(STUDENT_ID) 
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
print(f"{STUDENT_NAME}'s Array:", data) 
 
mean_val = np.mean(data) 
std_val = np.std(data) 
print("Mean:", mean_val, "Std Dev:", std_val)

Mark Aldred's Array: [ 7 28 68 65 89 79 29 65 47 20]
Mean: 49.7 Std Dev: 26.1114917229943


In [3]:
import numpy as np 

STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253
 
np.random.seed(STUDENT_ID) 
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
print(f"{STUDENT_NAME}'s Matrix:\n", matrix) 
 
row_sums = np.sum(matrix, axis=1) 
col_sums = np.sum(matrix, axis=0) 
print("Row sums:", row_sums) 
print("Column sums:", col_sums)

Mark Aldred's Matrix:
 [[ 7  4  1 21]
 [15 13  1 15]
 [20  1 12  8]]
Row sums: [33 44 41]
Column sums: [42 18 14 44]


In [4]:
import numpy as np 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3)) 
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d) 
 
slice_mid = arr3d[:,1,:] 
print("Slice[:,1,:]:\n", slice_mid)

Mark Aldred's 3D Array:
 [[[ 6  3  0]
  [20 14 12]
  [ 0 14 19]]

 [[ 0 11  7]
  [ 4 20 18]
  [14  9 13]]

 [[15 17 18]
  [20 11 17]
  [18 22  7]]]
Slice[:,1,:]:
 [[20 14 12]
 [ 4 20 18]
 [20 11 17]]


In [5]:
import numpy as np 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)] 
print(f"{STUDENT_NAME}'s Original:", x) 
print("Filtered subset:", filtered) 

Mark Aldred's Original: [ 7 28 68 65 89 79 29 65 47 20]
Filtered subset: [ 7 28 29 47 20]


In [6]:
import numpy as np 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
print("Matrix A:\n", A) 
print("Matrix B:\n", B) 
 
product = A @ B 
det_A = np.linalg.det(A) 
print("A @ B:\n", product) 
print("Determinant of A:", det_A) 

Matrix A:
 [[ 7  4]
 [ 1 21]]
Matrix B:
 [[15 13]
 [ 1 15]]
A @ B:
 [[109 151]
 [ 36 328]]
Determinant of A: 142.99999999999994


In [7]:
import numpy as np 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
angles = np.linspace(0, 2*np.pi, 8) 
sine_vals = np.sin(angles) 
cos_vals = np.cos(angles) 
print(f"{STUDENT_NAME}'s Angles:", angles) 
print("Sine:", sine_vals) 
print("Cosine:", cos_vals)

Mark Aldred's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [8]:
import numpy as np 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4)) 
arr[::2, ::2] = 0 
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr) 

Mark Aldred's Modified 4x4 Array:
 [[ 0  4  0 21]
 [15 13  1 15]
 [ 0  1  0  8]
 [ 5 21 19 15]]


In [9]:
import numpy as np 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10) 
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail') 
print(f"{STUDENT_NAME}'s Scores:", scores) 
print("Grades:", grades) 

Mark Aldred's Scores: [ 6 27 67 64 88 78 28 64 46 19]
Grades: ['Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Fail']


In [10]:
import numpy as np 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
flat_arr = arr.flatten() 
transposed_arr = arr.T 
print("Original array:\n", arr) 
print("Flattened:", flat_arr) 
print("Transposed:\n", transposed_arr)

Original array:
 [[ 7  4  1 21]
 [15 13  1 15]
 [20  1 12  8]]
Flattened: [ 7  4  1 21 15 13  1 15 20  1 12  8]
Transposed:
 [[ 7 15 20]
 [ 4 13  1]
 [ 1  1 12]
 [21 15  8]]


In [12]:
import numpy as np 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3)) 
mask = arr % 2 == 0 
arr[mask] = -1 
print("Array with conditional replacements:\n", arr) 

Array with conditional replacements:
 [[ 7 -1  1]
 [21 15 13]
 [ 1 15 -1]]


In [13]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name': [STUDENT_NAME]*5, 
    'Score': np.random.randint(STUDENT_ID%50, 
STUDENT_ID%100+50,5), 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
print(df) 

          Name  Score  YearsCodePro
0  Mark Aldred      9            14
1  Mark Aldred     30            12
2  Mark Aldred     70             0
3  Mark Aldred     67            14
4  Mark Aldred     91            19


In [14]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'], 
    # Corrected to use a functional salary range, e.g., 40000 to 150000 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean() 
print(avg_salary) 

EdLevel
Bachelor    103971.0
Master      119943.5
PhD          40067.0
Name: ConvertedComp, dtype: float64


In [15]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
top5 = df.sort_values(by='ConvertedComp', ascending=False) 
print(top5) 

       Country  ConvertedComp
4      Germany         134708
3       Canada         132864
1          USA         105179
0  Philippines          75078
2           UK          40067


In [16]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name':[STUDENT_NAME]*5, 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
high_exp = df[df['YearsCodePro']>STUDENT_ID%10] 
print(high_exp) 

          Name  YearsCodePro
0  Mark Aldred             6
3  Mark Aldred            20
4  Mark Aldred            14


In [17]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
bins = [0, 50000, 100000, 150000, 200000] 
labels = ['0-50k', '50-100k', '100-150k', '>150k'] 
 
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels) 
print(df) 

   ConvertedComp   Bracket
0          75078   50-100k
1         105179  100-150k
2          40067     0-50k
3         132864  100-150k
4         134708  100-150k


In [18]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
 
# Original Code Issue:  
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)  
# -> np.random.randint(12345, 12345, 5) which is a zero-length range. 
 
# Corrected Code: Using a functional salary range (40000 to 150000) 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
df['LogComp'] = np.log(df['ConvertedComp']) 
print(df)

   ConvertedComp    LogComp
0          75078  11.226283
1         105179  11.563419
2          40067  10.598308
3         132864  11.797081
4         134708  11.810865


In [19]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5), 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
corr_matrix = df.corr() 
print(corr_matrix) 

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.065209
ConvertedComp      0.065209       1.000000


In [23]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
# Calculate mean, median, and standard deviation for each 'EdLevel' 
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index() 
print(summary)

    EdLevel      mean    median           std
0  Bachelor  103971.0  103971.0  40860.872458
1    Master  119943.5  119943.5  20880.156142
2       PhD   40067.0   40067.0           NaN


In [24]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
 
# Generate salaries: [100727, 136195, 130612, 100727, 95233] 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
threshold = 110000 
 
# Create the 'HighPay' column using np.where() 
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No') 
 
print(df)

   ConvertedComp HighPay
0          75078      No
1         105179      No
2          40067      No
3         132864     Yes
4         134708     Yes


In [26]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Mark Aldred" 
STUDENT_ID = 1253 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5) 
}) 
 
# Group by 'Country' and calculate the mean and max 'ConvertedComp' 
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max']) 
print(top_countries) 

                 mean     max
Country                      
Canada       132864.0  132864
Germany      134708.0  134708
Philippines   75078.0   75078
UK            40067.0   40067
USA          105179.0  105179
