In [2]:
import numpy as np

# Step 1-2: Create 1D array with 2 additional data points [cite: 44, 58]
years_exp = np.array([1, 3, 5, 7, 10, 12, 15]) 
print("Years of Experience:", years_exp)

# Step 3: Create 2D array with 2 additional data points [cite: 47, 58]
# Added [110, 120] to the second row to expand the matrix
salaries = np.array([[50, 60, 70], [80, 90, 100], [110, 120, 130]])
print("Salary Matrix:\n", salaries)

# Step 4: Placeholder arrays [cite: 49, 50]
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

# Try It: Create a 3x3 identity matrix 
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

Years of Experience: [ 1  3  5  7 10 12 15]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# Step 1-2: Addition and Multiplication [cite: 61, 64]
exp_plus_5 = years_exp + 5
print("Years of Experience + 5:", exp_plus_5)
exp_times_2 = years_exp * 2
print("Years of Experience * 2:", exp_times_2)

# Try It: Subtraction and Division [cite: 71]
exp_minus_1 = years_exp - 1
print("Years of Experience - 1:", exp_minus_1)
exp_div_2 = years_exp / 2
print("Years of Experience / 2:", exp_div_2)

# Step 3: Dot product [cite: 68]
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

# Try It: Apply np.exp() and np.log() 
exp_transformed = np.exp(years_exp)
log_transformed = np.log(years_exp)
print("Exponential Transformed:", exp_transformed)
print("Logarithmic Transformed:", log_transformed)

Years of Experience + 5: [ 6  8 10 12 15 17 20]
Years of Experience * 2: [ 2  6 10 14 20 24 30]
Years of Experience - 1: [ 0  2  4  6  9 11 14]
Years of Experience / 2: [0.5 1.5 2.5 3.5 5.  6.  7.5]
Dot Product: 32
Exponential Transformed: [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04 1.62754791e+05 3.26901737e+06]
Logarithmic Transformed: [0.         1.09861229 1.60943791 1.94591015 2.30258509 2.48490665
 2.7080502 ]


In [9]:
# Indexing and Slicing [cite: 75, 77, 80]
# Step 1: Accessing elements
print("First Year of Experience:", years_exp[0])

# Step 2: Slicing arrays
print("First two salaries:", salaries[0, :2]) # First two elements of the first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1]) 

# Step 4: Negative indexing 
print("Last year of experience:", years_exp[-1]) 

# Reversing the flattened 1D array
reversed_1d = flattened_exp[::-1]
print("Reversed 1D Array:", reversed_1d)

# Reversing the 2D array (reverses the order of rows)
reversed_2d_rows = reshaped_exp[::-1]
print("\n2D Array with Rows Reversed:\n", reversed_2d_rows)

# Reversing both rows and columns
reversed_2d_all = reshaped_exp[::-1, ::-1]
print("\n2D Array Fully Reversed:\n", reversed_2d_all)

# Extract the first two columns of all rows
first_two_cols = reshaped_exp[:, 0:2]
print("First Two Columns (Subgroup):\n", first_two_cols)

# Extract a specific 'salary' (e.g., Row 1, Column 2)
specific_value = reshaped_exp[1, 2]
print("\nValue at Row 1, Col 2:", specific_value)

# Extract only the second row
second_row_only = reshaped_exp[1, :]
print("\nAll values in Second Row:", second_row_only)

First Year of Experience: 1
First two salaries: [50 60]
Second column salaries: [ 60  90 120]
Last year of experience: 15
Reversed 1D Array: [6 5 4 3 2 1]

2D Array with Rows Reversed:
 [[4 5 6]
 [1 2 3]]

2D Array Fully Reversed:
 [[6 5 4]
 [3 2 1]]
First Two Columns (Subgroup):
 [[1 2]
 [4 5]]

Value at Row 1, Col 2: 6

All values in Second Row: [4 5 6]


In [11]:
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis 
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3)) 
print("Reshaped Experience Array:\n", reshaped_exp) 

# Step 2: Flatten 2D arrays back into 1D 
flattened_exp = reshaped_exp.flatten() 
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example 
print("Transposed Array:\n", reshaped_exp.T)

# Try it: Reshape 1D array into a column vector for modeling
column_vector = years_exp.reshape(-1, 1)

print("Original Shape:", years_exp.shape)
print("New Shape for Modeling:", column_vector.shape)
print("\nColumn Vector:\n", column_vector)



Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
Original Shape: (7,)
New Shape for Modeling: (7, 1)

Column Vector:
 [[ 1]
 [ 3]
 [ 5]
 [ 7]
 [10]
 [12]
 [15]]


In [14]:
# Step 1: Add a bonus array to salaries using broadcasting 
bonus = np.array([5, 10, 15]) 
salaries_with_bonus = salaries + bonus  # Adds corresponding bonus to each column 
print("Salaries after bonus:\n", salaries_with_bonus)

# Try it: Multiply salaries by a scaling factor using broadcasting
scaling_factor = 1.1  # 10% increase
scaled_salaries = salaries * scaling_factor
print("Scaled Salaries:\n", scaled_salaries)


Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]
 [115 130 145]]
Scaled Salaries:
 [[ 55.  66.  77.]
 [ 88.  99. 110.]
 [121. 132. 143.]]


In [16]:
# Step 1: Mean of years of experience 
print("Mean experience:", np.mean(years_exp)) 

# Step 2: Standard deviation of experience 
print("Std deviation of experience:", np.std(years_exp)) 

# Step 3: Max and Min salaries 
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries)) 

# Step 4: Sum of salaries 
print("Sum of all salaries:", np.sum(salaries))

# Try it: Compute median or percentiles for arrays
print("\nMedian experience:", np.median(years_exp))
print("25th percentile of salaries:", np.percentile(salaries, 25))
print("75th percentile of salaries:", np.percentile(salaries, 75))

Mean experience: 7.571428571428571
Std deviation of experience: 4.655477353371521
Max salary: 130 Min salary: 50
Sum of all salaries: 810

Median experience: 7.0
25th percentile of salaries: 70.0
75th percentile of salaries: 110.0


In [ ]:
# Step 1: Apply trigonometric functions 
angles = np.array([0, np.pi/4, np.pi/2]) 
print("Sine of angles:", np.sin(angles)) 
print("Cosine of angles:", np.cos(angles)) 

# Step 2: Apply function along rows (sum salaries per person) 
salary_sums = np.apply_along_axis(np.sum, 1, salaries) 
print("Sum of Salaries per person:", salary_sums)

# Try it: 
# Use np.sqrt() or np.log() for transformations
# Apply custom functions with np.apply_along_axis()

sqrt_salaries = np.sqrt(salaries)
print("\nSquare Root of Salaries:\n", sqrt_salaries)

# Log transformation (standard for financial data to handle exponential growth)
# np.log is the natural log (ln)
log_salaries = np.log(salaries)
print("Log of Salaries:\n", log_salaries)


Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270 360]

Square Root of Salaries:
 [[ 7.07106781  7.74596669  8.36660027]
 [ 8.94427191  9.48683298 10.        ]
 [10.48808848 10.95445115 11.40175425]]
Log of Salaries:
 [[3.91202301 4.09434456 4.24849524]
 [4.38202663 4.49980967 4.60517019]
 [4.70048037 4.78749174 4.86753445]]


In [24]:
import pandas as pd

# Step 1: Create a NumPy array of random data 
data = np.random.randint(1, 50, size=(5, 3)) 

# Step 2: Convert the array into a DataFrame 
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z']) 
print("Generated Data:\n", df_data) 

# Step 3: Apply NumPy functions to DataFrame columns 
df_data['Log_X'] = np.log(df_data['X']) 
df_data['Sqrt_Y'] = np.sqrt(df_data['Y']) 
print("\nDataFrame with NumPy Transformations:\n", df_data) 

# Step 4: Analyze data using Pandas correlation 
print("\nCorrelation Matrix:\n", df_data.corr())

# Try it:
# - Use np.mean() and np.median() to compute overall column statistics
# - Apply other NumPy functions such as np.square() or np.exp()

# Compute Mean and Median for Column 'X'
mean_x = np.mean(df_data['X'])
median_x = np.median(df_data['X'])
overall_mean = np.mean(df_data, axis=0) 
print(f"\nColumn X - Mean: {mean_x:.2f}, Median: {median_x}")
print("\nOverall Column Means:\n", overall_mean)

# Square values in Column Z
df_data['Z_Squared'] = np.square(df_data['Z'])
# Exponential transformation to Column X
df_data['Exp_X'] = np.exp(df_data['X'])
print("\nUpdated DataFrame with Square and Exp:\n", df_data[['X', 'Z', 'Z_Squared', 'Exp_X']].head())

Generated Data:
     X   Y   Z
0  40  28  49
1  41  34   2
2  49  26  20
3  25  16  18
4   2   2  18

DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  40  28  49  3.688879  5.291503
1  41  34   2  3.713572  5.830952
2  49  26  20  3.891820  5.099020
3  25  16  18  3.218876  4.000000
4   2   2  18  0.693147  1.414214

Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.926676  0.116921  0.955538  0.948669
Y       0.926676  1.000000  0.018241  0.914145  0.987678
Z       0.116921  0.018241  1.000000  0.120925  0.061484
Log_X   0.955538  0.914145  0.120925  1.000000  0.965145
Sqrt_Y  0.948669  0.987678  0.061484  0.965145  1.000000

Column X - Mean: 31.40, Median: 40.0

Overall Column Means:
 X         31.400000
Y         21.200000
Z         21.400000
Log_X      3.041259
Sqrt_Y     4.327138
dtype: float64

Updated DataFrame with Square and Exp:
     X   Z  Z_Squared         Exp_X
0  40  49       2401  2.353853e+17
1  

In [25]:
# Step 1: Save the DataFrame to a CSV file 
df_data.to_csv('sample_data.csv', index=False) 
print("Data saved to 'sample_data.csv'.") 

# Step 2: Load the CSV file back into a new DataFrame 
df_imported = pd.read_csv('sample_data.csv') 
print("Imported DataFrame:\n", df_imported) 

# Step 3: Generate summary statistics 
summary_stats = df_imported.describe() 
print("Summary Statistics:\n", summary_stats) 

# Step 4: Display column means and standard deviations 
print("Column Means:\n", df_imported.mean()) 
print("Column Standard Deviations:\n", df_imported.std())

# Try it:
# Add a new calculated column (e.g., df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y'])
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
print("\nDataFrame with Sum_XY Column:\n", df_imported[['X', 'Y', 'Sum_XY']].head())
# Save the modified DataFrame to a new CSV file and review
df_imported.to_csv('modified_sample_data.csv', index=False)
print("Modified data saved to 'modified_sample_data.csv'.")

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y  Z_Squared         Exp_X
0  40  28  49  3.688879  5.291503       2401  2.353853e+17
1  41  34   2  3.713572  5.830952          4  6.398435e+17
2  49  26  20  3.891820  5.099020        400  1.907347e+21
3  25  16  18  3.218876  4.000000        324  7.200490e+10
4   2   2  18  0.693147  1.414214        324  7.389056e+00
Summary Statistics:
               X          Y          Z     Log_X    Sqrt_Y    Z_Squared  \
count   5.00000   5.000000   5.000000  5.000000  5.000000     5.000000   
mean   31.40000  21.200000  21.400000  3.041259  4.327138   690.600000   
std    18.58225  12.537942  17.052859  1.336043  1.759219   968.262258   
min     2.00000   2.000000   2.000000  0.693147  1.414214     4.000000   
25%    25.00000  16.000000  18.000000  3.218876  4.000000   324.000000   
50%    40.00000  26.000000  18.000000  3.688879  5.099020   324.000000   
75%    41.00000  28.000000  20.000000  3.713572  5.29

In [43]:
# Step 1: Load the dataset
# Added low_memory=False to remove the warning you saw
df_kaggle = pd.read_csv('survey_results_public.csv', low_memory=False) 

# Step 2: Select the correct columns based on your file's actual names
# We are using 'WorkExp' instead of 'YearsCodePro' and 'ConvertedCompYearly' for salary
df_subset = df_kaggle[['Country', 'EdLevel', 'WorkExp', 'ConvertedCompYearly']].copy()

# Step 3: Clean the data
df_clean = df_subset.dropna().copy()

# Step 4: Categorize experience into groups 
# Since WorkExp is already a number, we don't need to convert it!
df_clean['ExperienceLevel'] = np.where(df_clean['WorkExp'] >= 10, 'Senior', 'Junior') 

# Step 5: Group data by Country and ExperienceLevel, compute average salary 
# Note: Using ConvertedCompYearly here
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()

# Step 6: Reset index for readability 
grouped_data = grouped_data.reset_index() 

print("--- Success! Formatted Grouped Data ---")
print(grouped_data.head(10))

# Try it: 
import pandas as pd

# --- Step 1: Education Level Analysis ---
# We calculate mean, median, and standard deviation in one clean command
ed_stats = df_clean.groupby(['Country', 'EdLevel'])['ConvertedCompYearly'].agg(['mean', 'median', 'std']).reset_index()

# Rename for professional presentation
ed_stats.columns = ['Country', 'Education_Level', 'Avg_Salary', 'Median_Salary', 'Std_Dev']

# Round the numbers to 2 decimal places so they look like currency
ed_stats = ed_stats.round(2)

print("\n--- Salary Statistics by Education Level (First 10) ---")
print(ed_stats.head(10))


# --- Step 2: High-Earner Analysis ---
# Find the top 10 countries based on average compensation
top_countries = ed_stats.sort_values(by='Avg_Salary', ascending=False).head(10)

print("\n--- Top 10 Countries with Highest Average Compensation ---")
# to_string(index=False) makes it look like a clean report instead of a raw dataframe
print(top_countries[['Country', 'Education_Level', 'Avg_Salary']].to_string(index=False))


--- Success! Formatted Grouped Data ---
               Country ExperienceLevel  ConvertedCompYearly
0          Afghanistan          Junior         13831.142857
1              Albania          Junior         30752.000000
2              Albania          Senior         65195.166667
3              Algeria          Junior          8910.800000
4              Algeria          Senior         49543.000000
5              Andorra          Junior        348044.000000
6              Andorra          Senior        162337.000000
7               Angola          Junior        149857.250000
8  Antigua and Barbuda          Senior             1.000000
9            Argentina          Junior         28036.518519

--- Salary Statistics by Education Level (First 10) ---
       Country                                    Education_Level  Avg_Salary  \
0  Afghanistan       Bachelor’s degree (B.A., B.S., B.Eng., etc.)      4644.0   
1  Afghanistan    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)      4014.0   
